# Generated by Django 3.2.15 on 2023-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20230114_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('EL', 'Электронными'), ('CS', 'Наличными')], db_index=True, default='CS', max_length=2, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=200, verbose_name='Адрес доставки'),
        ),
    ]
