# Generated by Django 3.2.15 on 2023-01-14 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230114_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_orders', to='foodcartapp.restaurant', verbose_name='Готовит ресторан'),
        ),
    ]
