# Generated by Django 3.2.15 on 2023-01-20 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='cooks_restaurant',
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_method',
            field=models.CharField(choices=[('EL', 'Электронными'), ('CS', 'Наличными'), ('UN', 'Не назначено')], db_index=True, default='UN', max_length=2, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='foodcartapp.order', verbose_name='заказ'),
        ),
        migrations.AlterField(
            model_name='orderelement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='foodcartapp.product', verbose_name='товар'),
        ),
    ]
