# Generated by Django 3.2.15 on 2023-01-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20230120_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='foodcartapp.OrderElement', to='foodcartapp.Product', verbose_name='Продукты'),
        ),
    ]
