# Generated by Django 3.2.15 on 2023-01-12 12:40

from django.db import migrations, models
import foodcartapp.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон')),
                ('delivery_address', models.TextField(verbose_name='Адрес доставки')),
                ('product', models.ForeignKey(on_delete=foodcartapp.models.Product, related_name='Продукт', to='foodcartapp.product')),
            ],
        ),
    ]
