# Generated by Django 3.2.15 on 2023-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_products'),
    ]

    operations = [
    ]
