# Generated by Django 3.2.15 on 2023-01-14 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_status', '-created_at'], 'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
    ]
